### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by kingdom3219** [tahayasinkuloglu/RiseOfKingdoms-KingdomManager#1]
How can I setup this?

**Comment by kingdom3219** [comment]
what does the .env look like?

**Comment by tahayasinkuloglu** [comment]
Create a file named **.env** in the home directory. Then save _MONGO_URI=mongodb+srv://"your cluster info"_ in it.

**Comment by kingdom3219** [comment]
`db connection fail:  MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (/var/task/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206:11)
    at NativeConnection.openUri (/var/task/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/var/task/node_modules/mongoose/lib/index.js:404:15)
    at dbConnect (/var/task/.next/server/pages/api/login.js:27:82)
    at login (/var/task/.next/server/pages/api/login.js:62:78)
    at Handler (/var/task/.next/server/pages/api/login.js:54:20)
    at /var/task/node_modules/next/dist/server/api-utils/node.js:463:16
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (/var/task/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206:11)
    at NativeConnection.openUri (/var/task/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/var/task/node_modules/mongoose/lib/index.js:404:15)
    at dbConnect (/var/task/.next/server/pages/api/login.js:27:82)
    at login (/var/task/.next/server/pages/api/login.js:62:78)
    at Handler (/var/task/.next/server/pages/api/login.js:54:20)
    at /var/task/node_modules/next/dist/server/api-utils/node.js:463:16
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (/var/task/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:206:11)
    at NativeConnection.openUri (/var/task/node_modules/mongoose/lib/connection.js:738:34)
    at Mongoose.connect (/var/task/node_modules/mongoose/lib/index.js:404:15)
    at dbConnect (/var/task/.next/server/pages/api/login.js:27:82)
    at login (/var/task/.next/server/pages/api/login.js:62:78)
    at Handler (/var/task/.next/server/pages/api/login.js:54:20)
    at /var/task/node_modules/next/dist/server/api-utils/node.js:463:16
    at /var/task/node_modules/next/dist/server/lib/trace/tracer.js:117:36
    at NoopContextManager.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7057)
    at ContextAPI.with (/var/task/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:516)
Error: Runtime exited with error: exit status 1
Runtime.ExitError
`

already did that but still having errors

**Comment by kingdom3219** [comment]
MONGO_URI=mongodb+srv://<user>:<password>@<cluster>.1drdz6m.mongodb.net/?retryWrites=true&w=majority

that's my env looks like
